baseURL = "https://thinkfarmberlin.github.io/"
title = "Thinkfarm"
disableKinds = ["taxonomy", "term"]

[outputs]
home  = ["HTML"]

[markup.goldmark.parser]
autoHeadingID = true

[markup.goldmark.renderer]
unsafe = true  # allow HTML in markdown files
